# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spvplayer.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 680)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 471, 81))
        self.groupBox.setObjectName("groupBox")
        self.buttonUartRefresh = QtWidgets.QPushButton(self.groupBox)
        self.buttonUartRefresh.setGeometry(QtCore.QRect(10, 40, 89, 25))
        self.buttonUartRefresh.setObjectName("buttonUartRefresh")
        self.comboBoxUart = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxUart.setGeometry(QtCore.QRect(110, 40, 131, 25))
        self.comboBoxUart.setObjectName("comboBoxUart")
        self.buttonUartConnect = QtWidgets.QPushButton(self.groupBox)
        self.buttonUartConnect.setGeometry(QtCore.QRect(250, 40, 89, 25))
        self.buttonUartConnect.setObjectName("buttonUartConnect")
        self.UartStatusIndicator = QtWidgets.QLabel(self.groupBox)
        self.UartStatusIndicator.setGeometry(QtCore.QRect(350, 40, 101, 17))
        self.UartStatusIndicator.setObjectName("UartStatusIndicator")
        self.buttonTest = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTest.setGeometry(QtCore.QRect(40, 120, 89, 25))
        self.buttonTest.setObjectName("buttonTest")
        self.buttonGetStatus = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGetStatus.setGeometry(QtCore.QRect(270, 170, 161, 25))
        self.buttonGetStatus.setObjectName("buttonGetStatus")
        self.buttonRequestChannelFill = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRequestChannelFill.setGeometry(QtCore.QRect(270, 210, 161, 25))
        self.buttonRequestChannelFill.setObjectName("buttonRequestChannelFill")
        self.buttonStartPlaying = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStartPlaying.setGeometry(QtCore.QRect(270, 290, 161, 25))
        self.buttonStartPlaying.setObjectName("buttonStartPlaying")
        self.buttonStopPlaying = QtWidgets.QPushButton(self.centralwidget)
        self.buttonStopPlaying.setGeometry(QtCore.QRect(270, 330, 161, 25))
        self.buttonStopPlaying.setObjectName("buttonStopPlaying")
        self.buttonInitSPV = QtWidgets.QPushButton(self.centralwidget)
        self.buttonInitSPV.setGeometry(QtCore.QRect(270, 250, 161, 25))
        self.buttonInitSPV.setObjectName("buttonInitSPV")
        self.buttonRewind = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRewind.setGeometry(QtCore.QRect(40, 210, 161, 25))
        self.buttonRewind.setObjectName("buttonRewind")
        self.buttonClearChannels = QtWidgets.QPushButton(self.centralwidget)
        self.buttonClearChannels.setGeometry(QtCore.QRect(270, 370, 161, 25))
        self.buttonClearChannels.setObjectName("buttonClearChannels")
        self.buttonReadMcode = QtWidgets.QPushButton(self.centralwidget)
        self.buttonReadMcode.setGeometry(QtCore.QRect(40, 170, 161, 25))
        self.buttonReadMcode.setObjectName("buttonReadMcode")
        self.buttonMoveENoteTo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMoveENoteTo.setGeometry(QtCore.QRect(480, 170, 161, 25))
        self.buttonMoveENoteTo.setObjectName("buttonMoveENoteTo")
        self.buttonMovePosxTo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMovePosxTo.setGeometry(QtCore.QRect(480, 210, 161, 25))
        self.buttonMovePosxTo.setObjectName("buttonMovePosxTo")
        self.buttonMovePosyTo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMovePosyTo.setGeometry(QtCore.QRect(480, 250, 161, 25))
        self.buttonMovePosyTo.setObjectName("buttonMovePosyTo")
        self.buttonMoveStrTo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonMoveStrTo.setGeometry(QtCore.QRect(480, 290, 161, 25))
        self.buttonMoveStrTo.setObjectName("buttonMoveStrTo")
        self.textinENotePos = QtWidgets.QLineEdit(self.centralwidget)
        self.textinENotePos.setGeometry(QtCore.QRect(650, 170, 61, 25))
        self.textinENotePos.setObjectName("textinENotePos")
        self.textinPosxPos = QtWidgets.QLineEdit(self.centralwidget)
        self.textinPosxPos.setGeometry(QtCore.QRect(650, 210, 61, 25))
        self.textinPosxPos.setObjectName("textinPosxPos")
        self.textinPosyPos = QtWidgets.QLineEdit(self.centralwidget)
        self.textinPosyPos.setGeometry(QtCore.QRect(650, 250, 61, 25))
        self.textinPosyPos.setInputMask("")
        self.textinPosyPos.setObjectName("textinPosyPos")
        self.textinStrPos = QtWidgets.QLineEdit(self.centralwidget)
        self.textinStrPos.setGeometry(QtCore.QRect(650, 290, 61, 25))
        self.textinStrPos.setObjectName("textinStrPos")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 932, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SPV Player"))
        self.groupBox.setTitle(_translate("MainWindow", "Serial connection"))
        self.buttonUartRefresh.setText(_translate("MainWindow", "Refresh"))
        self.buttonUartConnect.setText(_translate("MainWindow", "Connect"))
        self.UartStatusIndicator.setText(_translate("MainWindow", "Disconnected"))
        self.buttonTest.setText(_translate("MainWindow", "Test"))
        self.buttonGetStatus.setText(_translate("MainWindow", "Get Status"))
        self.buttonRequestChannelFill.setText(_translate("MainWindow", "Request Channel Fill"))
        self.buttonStartPlaying.setText(_translate("MainWindow", "Start Playing"))
        self.buttonStopPlaying.setText(_translate("MainWindow", "Stop Playing"))
        self.buttonInitSPV.setText(_translate("MainWindow", "Init Channels"))
        self.buttonRewind.setText(_translate("MainWindow", "Rewind"))
        self.buttonClearChannels.setText(_translate("MainWindow", "Clear Channels"))
        self.buttonReadMcode.setText(_translate("MainWindow", "Read M-Code"))
        self.buttonMoveENoteTo.setText(_translate("MainWindow", "Move e-note to"))
        self.buttonMovePosxTo.setText(_translate("MainWindow", "Move POSX to"))
        self.buttonMovePosyTo.setText(_translate("MainWindow", "Move POSY to"))
        self.buttonMoveStrTo.setText(_translate("MainWindow", "Move STR to"))
        self.textinENotePos.setText(_translate("MainWindow", "0"))
        self.textinPosxPos.setText(_translate("MainWindow", "0"))
        self.textinPosyPos.setText(_translate("MainWindow", "0"))
        self.textinStrPos.setText(_translate("MainWindow", "0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open m-code"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

